services:

  backend:
    build: ./backend
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    environment:
      - PORT=$PORT
      - TICK_RATE=$TICK_RATE
    command: npm run dev

  frontend:
    environment:
      - VITE_WS_URL=$WS_URL
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    command: npm run dev
